### ISSUE TITLE
Is there a way to get all waiting jobs in an array?

### ISSUE THREAD

**Issue by ethanjyx** [chrisboulton/php-resque#240]
I'm sorry if I missed anything in the doc. It seems that we can only query the status of a specific job.

**Comment by danhunsaker** [comment]
You can use the underlying Redis implementation to get the contents of the queue's list, which should be an array.  The key is `resque:queue:<name>`.

**Comment by ethanjyx** [comment]
I read a little of Rescue.php, do I do

self::redis()->get("queue_name")?

**Comment by danhunsaker** [comment]
`$self->redis()->lrange('queue:queue_name', 0, -1);`

Check out redis.io/commands for more.

**Comment by ethanjyx** [comment]
Right. That can find all the waiting jobs. But is there a way to get all the running jobs as well? I find the running jobs are not in the return value from that command. Thanks.

**Comment by danhunsaker** [comment]
The currently-running jobs won't be in the queue still, no.  To find those, you need to do a couple of steps.  First, get a list of the workers currently running (from `queues`).  Then, iterate through that list and retrieve the value of each worker's "current job" key (I forget which one this is at the moment, but the HOWITWORKS.md should say).

Keep in mind that you may get a job twice - once in the queue list, and once in the currently-running list - because the time taken to retrieve the currently-running list may be long enough for one or more of the workers to finish a job, and start the next one on the queue.
