### ISSUE TITLE
Inconsistent payload data types documented in Resque_Job

### ISSUE THREAD

**Issue by elazar** [chrisboulton/php-resque#242]
See [this line](https://github.com/chrisboulton/php-resque/blob/eb7ab0c81ada61f11f27d3069d48d7bb82ee4670/lib/Resque/Job.php#L22), which states that the `$payload` property has an `object` type, versus [this line](https://github.com/chrisboulton/php-resque/blob/eb7ab0c81ada61f11f27d3069d48d7bb82ee4670/lib/Resque/Job.php#L35), which states that the `$payload` property has an `array` type.

I believe `array` to be correct. I'm guessing that this type was changed at some point and that particular type referenced was simply overlooked when updating documentation?

**Comment by danhunsaker** [comment]
I'm not certain the inline documentation was ever really looked at too hard.  In all honesty, though, it could easily be either, since the payload gets JSON-encoded between enqueue and work start.

That said, a PR with `array` would probably be accepted.  @chrisboulton is pretty busy lately, though, so I can't speak to how quickly, though.

**Comment by elazar** [comment]
Submitted #246.

**Comment by chrisboulton** [comment]
Thanks :)
