### ISSUE TITLE
How to Correctly Send Signals to Workers?

### ISSUE THREAD

**Issue by Twinsen343** [chrisboulton/php-resque#245]
Hey Guys,

I have had a look at the demo's and done some extensive research and can't find an exact method or example with how to send a signal the a worker.

When a job runs, I store the PID of the PHP script in a database via
* getmypid()

I then have tried to find a way to send the commands listed in the README to the PID... I have found via my search in Google

* posix_kill( PID, SIGNAL )

This allows me to send a signal to the PID... which is exactly what I want.. however none of the accepted values match the values supplied in the readme.

* SIGUSR1

It wouldn't accept SIGUSR1 as a parameter, so on my setup I ran

* kill -l (this gave me the int value of the command which was 10 in my case)

This seems close to what I need, to I am using this -> however the command posix_kill fails..

I have a "health" script which runs every few mins to check things are progressing and if something times out and gets stuck... which is possible, then I can send a signal to free up  the worker..

What is the general accepted method in sending signals to workers via the PID?

I'm using Ubuntu 12.04 and using php 5.3+

Thanks heaps

**Comment by danhunsaker** [comment]
First off, you probably don't want to send the signal to the job's PID - you'll usually want the worker's PID, which is different because Resque forks itself before each job.  `SIGUSR1`, especially, won't work when pointed at the job's PID, since the signal handler is set up to terminate a child process, which won't exist in the job's fork.  There are a couple of ways to get this - you could use `posix_getppid()` in your job instead of `getmypid()`, for example.  Or you can grab the worker PIDs from Redis, where they are all stored in the `resque:workers` set as `{$hostname}:{$pid}:{$queues}`.  Since you didn't specify how your health script iterates through your system, I can't tell whether you already have those PIDs available in other ways.

Second, `SIGUSR1` is highly preferred over hard-coding the integer value.  Check that the pcntl extension is installed and enabled in CLI mode on your system (most systems have a different config file for each SAPI), as that's where these constants are defined.

Third, you say `posix_kill()` fails, but you don't say how.  It could be considered a failure, for example, if sending the signal simply doesn't kill the job as expected (which it wouldn't, as explained above).  I suspect that isn't the case, here, but I can't confirm that without more information.

You've got the gist of it, we just need to figure out a few of the details.

**Comment by Twinsen343** [comment]
Hey

Thanks so much for your detailed response, upon further digging, I found I did not enable the pcntl extension on this particular server, with that enabled the <code>SIGUSR1</code> doesn't raise any exceptions.

I modified my query to save the PID via  <code>posix_getppid()</code> and can confirm when I run 
<code>  ps -e -o pid,command | grep [r]esque</code> it shows the PID there.

I still can't seem to get <code>posix_kill</code> to work... it always returns false even with the correct PID shown and the actual <code>SIGUSR1</code>  command.

My health script operates over a cron job which executes every minute > I will bring over to a redis job when it's all working.... if it detects with parameters I set that a job is hung, then it sends the command via the above to the processed which is meant to end the job and free up the worker
