### ISSUE TITLE
can use in php 5.2?

### ISSUE THREAD

**Issue by jinleileiking** [chrisboulton/php-resque#255]

**Comment by danhunsaker** [comment]
There are a couple of things used in the latest versions of PHP-Resque that require 5.3+.  I forget, offhand, what those are, exactly, but you might find a version that will run on 5.2 if you roll back the repo far enough.  Of course, that means missing out on features and bug fixes introduced since then, so it really isn't recommended.

Honestly, though, if you're on a host that's still using 5.2, it's either time to convince the sysadmin to upgrade, or move to a new host.  Most hosts are running at least 5.4 by now, and most Linux distros are shipping with 5.6 in their repos.  And 7.0 is coming (they discontinued 6.x because of issues that caused a bad reputation).  So there's not much excuse left for running 5.2 anymore.

**Comment by jinleileiking** [comment]
@danhunsaker Thanks a lot :+1:
