### ISSUE TITLE
How to reduce Payload length and jobs waiting for long time

### ISSUE THREAD

**Issue by arunp27** [chrisboulton/php-resque#270]
Hi I'm using PHP-resque for one of the project since more than 6 months. recently i got an issue like some times few jobs are not pushing in queue properly, i'm expecting the issue might be with payload size. sample payload is "b3742d946022a001c927df10f960247f". this is around 32 characters it is having, please suggest me how to reduce payload length as well as what might be other reasons if jobs not get to Processing state from being waiting stage.

**Comment by danhunsaker** [comment]
32 characters is pretty small.  It's not very likely that the payload size is your issue, since Redis is designed to handle values that are several megabytes in size.

It's more likely that your payloads are having trouble when they are JSON-encoded just before being sent to Redis.  There are a couple of pull requests designed to check for such failures so you can handle them accordingly, but until they're merged, you'll have to check that yourself, and handle it accordingly.

**Comment by arunp27** [comment]
Thanks danhunsaker.
