### ISSUE TITLE
How to add a payload directly from redis-cli?

### ISSUE THREAD

**Issue by Webonaute** [chrisboulton/php-resque#278]
Hi.

I probably a noob question but how I can add payload directly from redis-cli. how the command should like?
I ask this because I have a bash script who will fill the queue than my php application will take the relay and process the payload.

Thank.

**Comment by danhunsaker** [comment]
Your Bash script would need to generate a JSON object with the job id (an md5 hash in hexadecimal encoding works, but you'll want this to be a unique hash, so avoid hashing the payload itself, since that's not guaranteed to be unique), fully-namespaced class name, and object containing the job's arguments, then push that onto your queue.  Check HOWITWORKS.md for more details on that.

Alternately, your bash script could always call a small PHP script with just a `Resque->enqueue()` in it, and let the existing code handle it.  This is probably the approach I would take.

**Comment by Webonaute** [comment]
ok thank, yeah finally I used php to do it. less complicated.
