### ISSUE TITLE
PHP Resque plugins?

### ISSUE THREAD

**Issue by RVN-BR** [chrisboulton/php-resque#279]
Hi,

Apart from php-resque-scheduler, are there any other plugins/addons?

Maybe it would be cool to have a section for these links on the readme?

Is scheduler still being maintained?  Will the "cron-like" capacities be introduced officially? I know someone wrote a class for that, but I'm wondering....

**Comment by danhunsaker** [comment]
None that I remember seeing, but it's been a while since I searched last.

Agreed.  :-) 

It's as actively maintained as PHP-Resque itself.  Anyone is welcome to submit a PR which implements the cron-like functionality at any time, though it will take just as long to merge there as it does for things here.  So it might be a while.

**Comment by RVN-BR** [comment]
Great... I'll try and look at how the cron class works... if I can make a pr I will but i didnt even look at it yet... but I'm quite interested in using it :)
