### ISSUE TITLE
Catch \Throwable in perform()

### ISSUE THREAD

**Issue by jasverix** [chrisboulton/php-resque#343]
If an PHP Throwable error occurs, the process stops without failing the job first. The job is completly removed from Redis with all data.

**Comment by danhunsaker** [comment]
It currently catches all `\Exception` objects thrown, but since it's written for PHP 5.x, the `\Error` type Throwable didn't exist yet, so no, it isn't properly intercepted. This will certainly need to be addressed before PHP 5.6 reaches EOL, but in the meantime, PHP 7.x isn't, technically, fully supported.

**Comment by jasverix** [comment]
Currently, I catched \Throwable outside of ->work() and ran unregisterWorker() there. Then a DirtyExitException is set to the job, and it was registered as failed.

Before I did that, the jobs were just dropped with no trace.. please write somewhere that PHP 7 is not fully supported yet.

**Comment by jaredk2g** [comment]
Also check out #316 for PHP 7 support. We've been using this in production at work and it works well with PHP 7 errors.

**Comment by danhunsaker** [comment]
This has been applied in the new upstream, resque/php-resque.
